// Re-export drizzle query helpers, чтобы apps использовали ту же копию drizzle-orm,
// что и @x10/db. Иначе peer-dep дубликаты в pnpm-store ломают типы (см. CLAUDE.md §8).
export {
  and,
  asc,
  between,
  desc,
  eq,
  exists,
  gt,
  gte,
  ilike,
  inArray,
  isNotNull,
  isNull,
  like,
  lt,
  lte,
  ne,
  not,
  notExists,
  notInArray,
  or,
  sql,
} from "drizzle-orm";
