-- Встроенный магазин (спека 7, 15.08.2026).
--
-- Труба ОДНА на пополнение баланса и на продажу завода: одна таблица платежей,
-- один вебхук, одно место зачисления. Различает назначение (`purpose`), а не
-- отдельный код: два платёжных кода — это две правды о деньгах и два места, где
-- можно забыть чек 54-ФЗ.
--
-- Новых таблиц нет. Расширяются три существующие: платежи получают назначение и
-- связь с заказом, сделка становится заказом со ссылкой на оплату, партнёр —
-- налоговый статус.

-- ── 1. Платежи: назначение и заказ ───────────────────────────────────────
-- DEFAULT 'topup' — потому что до этой миграции таблица знала только пополнение
-- баланса (Спека 6). Существующие строки остаются собой.
ALTER TABLE "payments" ADD COLUMN IF NOT EXISTS "purpose" varchar(16) NOT NULL DEFAULT 'topup';
ALTER TABLE "payments" ADD COLUMN IF NOT EXISTS "deal_id" uuid
  REFERENCES "partner_deals"("id") ON DELETE SET NULL;
-- Что клиент видит в банке и в чеке. Одна строка на оба места.
ALTER TABLE "payments" ADD COLUMN IF NOT EXISTS "description" text;

-- ⚠️ varchar + CHECK, а не PG-enum: третье назначение (ежемесячное
-- сопровождение) мы уже знаем, что добавим, а enum не умеет DROP VALUE. Мёртвые
-- значения рубрикатора проект носит с X10-эпохи — второй раз не наступаем.
ALTER TABLE "payments" DROP CONSTRAINT IF EXISTS "payments_purpose_chk";
ALTER TABLE "payments" ADD CONSTRAINT "payments_purpose_chk"
  CHECK ("purpose" IN ('topup', 'entry'));

-- Платёж за вход обязан знать свой заказ, иначе комиссию партнёру начислять не
-- от чего. Пополнение баланса, наоборот, заказа не имеет никогда.
ALTER TABLE "payments" DROP CONSTRAINT IF EXISTS "payments_deal_purpose_chk";
ALTER TABLE "payments" ADD CONSTRAINT "payments_deal_purpose_chk"
  CHECK (("purpose" = 'entry' AND "deal_id" IS NOT NULL)
      OR ("purpose" = 'topup' AND "deal_id" IS NULL));

CREATE INDEX IF NOT EXISTS "payments_deal_idx" ON "payments" ("deal_id");

-- ── 2. Сделка становится заказом ─────────────────────────────────────────
-- Сквозной номер. Он же номер счёта: два разных номера у одного заказа — это
-- спор с бухгалтерией клиента на ровном месте.
ALTER TABLE "partner_deals" ADD COLUMN IF NOT EXISTS "deal_no" integer
  GENERATED BY DEFAULT AS IDENTITY;
CREATE UNIQUE INDEX IF NOT EXISTS "partner_deals_no_uidx" ON "partner_deals" ("deal_no");

-- Код ссылки на оплату: app.pro-agent-ai.ru/pay/<token>. Одна ссылка на весь
-- заказ, а не на каждую часть рассрочки: через месяц клиент возвращается по ней
-- же за второй половиной, и напоминание ведёт туда же.
ALTER TABLE "partner_deals" ADD COLUMN IF NOT EXISTS "pay_token" varchar(32);
CREATE UNIQUE INDEX IF NOT EXISTS "partner_deals_token_uidx"
  ON "partner_deals" ("pay_token") WHERE "pay_token" IS NOT NULL;

-- Частей оплаты: 1 или 2. Потолок — решение владельца (MAX_INSTALLMENT_MONTHS),
-- и живёт он правилом в базе, а не памятью продающего.
ALTER TABLE "partner_deals" ADD COLUMN IF NOT EXISTS "installments" smallint NOT NULL DEFAULT 1;
ALTER TABLE "partner_deals" DROP CONSTRAINT IF EXISTS "partner_deals_installments_chk";
ALTER TABLE "partner_deals" ADD CONSTRAINT "partner_deals_installments_chk"
  CHECK ("installments" BETWEEN 1 AND 2);

-- Кто платит. От этого зависит, предлагаем ли счёт по реквизитам: юрлицу безнал
-- дешевле на ~3% эквайринга, на линии это 10 500 ₽ с каждой продажи.
ALTER TABLE "partner_deals" ADD COLUMN IF NOT EXISTS "payer_kind" varchar(16);
ALTER TABLE "partner_deals" DROP CONSTRAINT IF EXISTS "partner_deals_payer_kind_chk";
ALTER TABLE "partner_deals" ADD CONSTRAINT "partner_deals_payer_kind_chk"
  CHECK ("payer_kind" IS NULL OR "payer_kind" IN ('individual', 'company'));

-- Реквизиты для счёта. Пусто у физлица.
ALTER TABLE "partner_deals" ADD COLUMN IF NOT EXISTS "payer_name" varchar(200);
ALTER TABLE "partner_deals" ADD COLUMN IF NOT EXISTS "payer_inn" varchar(12);
ALTER TABLE "partner_deals" ADD COLUMN IF NOT EXISTS "payer_kpp" varchar(9);
ALTER TABLE "partner_deals" ADD COLUMN IF NOT EXISTS "payer_address" text;

-- Почта плательщика: без неё облачная касса не выбьет чек (54-ФЗ).
ALTER TABLE "partner_deals" ADD COLUMN IF NOT EXISTS "payer_email" varchar(254);

-- Когда клиент принял оферту. Акцепт без отметки недоказуем, а продаём мы на
-- 350 000 ₽.
ALTER TABLE "partner_deals" ADD COLUMN IF NOT EXISTS "offer_accepted_at" timestamptz;

-- Срок второй части. Заполняется в момент оплаты первой: до этого срока нет.
ALTER TABLE "partner_deals" ADD COLUMN IF NOT EXISTS "next_due_at" timestamptz;

-- 🔴 Владелец продаёт и без партнёра, и это должен быть ТОТ ЖЕ заказ с той же
-- ссылкой и тем же счётом, а не отдельная ветка кода. Нет партнёра — нет
-- начислений, всё остальное одинаково.
ALTER TABLE "partner_deals" ALTER COLUMN "partner_id" DROP NOT NULL;

-- ── 3. Налоговый статус партнёра ─────────────────────────────────────────
-- Партнёры бывают любые, включая обычных физлиц (решение владельца 15.08). С
-- физлицом мы налоговый агент: удерживаем НДФЛ из его 20% и платим взносы СФР
-- сверх. Без этого поля выплата считается руками и ошибается.
ALTER TABLE "partners" ADD COLUMN IF NOT EXISTS "tax_status" varchar(16);
ALTER TABLE "partners" DROP CONSTRAINT IF EXISTS "partners_tax_status_chk";
ALTER TABLE "partners" ADD CONSTRAINT "partners_tax_status_chk"
  CHECK ("tax_status" IS NULL OR "tax_status" IN ('self_employed', 'entrepreneur', 'individual'));

-- ИНН: нужен для чека НПД от самозанятого и для отчётности по физлицу.
-- Спрашиваем при первом начислении, а не при регистрации: вход в программу
-- остаётся в один тап.
ALTER TABLE "partners" ADD COLUMN IF NOT EXISTS "inn" varchar(12);
